"""Create order_card table

Revision ID: 66867047cc7c
Revises: 
Create Date: 2023-12-04 01:21:15.070087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66867047cc7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('order_card')
    # ### end Alembic commands ###
